# new_house={'楼盘名称':'property_name',
# '楼盘特点':'property_features',
# '参考单价':'reference_unit_price',
# '物业类型':'property_type',
# '开发商':'developer',
# '区域位置':'regional_location',
# '楼盘地址':'property_address',
# '售楼处电话':'sales_office_phone',
# '最低首付':'minimum_down_payment',
# '开间面积':'opening_area',
# '办公室面积':'office_area',
# '楼盘户型':'real_estate_type',
# '招租客群':'tenant_group',
# '临近CBD':'near_cbd',
# '已签约租户':'contracted_tenant',
# '公共部分精装修':'public_decoration',
# '标准层面积':'standard_floor_area',
# '写字楼类型':'office_type',
# '写字楼级别':'office_level',
# '规划户数':'number_of_planned_households',
# '楼盘总价':'total_price_of_the_property',
# '绿化率':'greening_rate',
# '商业面积':'commercial_area',
# '总建筑面积':'total_surface_area',
# '最新开盘':'latest_opening',
# '交房时间':'delivery_time',
# '招商业态':'business_mode',
# '已签约商户':'contracted_merchant',
# '临近商圈':'near_business_district',
# '周边人群':'surrounding_crowd',
# '售楼处地址':'sales_office_address',
# '预售许可证':'presale_permit',
# '产权年限':'year_of_property_rights',
# '出售类型':'type_of_sale',
# '得房率':'toom_rate',
# '总套数':'total_number_of_sets',
# '楼层状况':'floor_condition',
# '工程进度':'project_progress',
# '物业管理费':'property_management_fees',
# '物业公司':'property_company',
# '车位数':'number_of_car',
# '车位比':'parking_ratio',
# '是否统一管理':'uniform_management',
# '是否分割':'whether_to_split',
# '出租类型':'type_of_rental',
# '租金':'rent',
# '是否包含物业费':'include_property_fees',
# '待租面积':'area_to_be_rented',
# '待租套数':'number_of_rents_to_be_rented',
# '省份':'province',
# '城市':'city',
# '区':'county',}


from xpinyin import Pinyin
pin = Pinyin()
# test1 = pin.get_pinyin("大河向东流")   #默认分割符为-
# print(test1)

test2 = pin.get_pinyin("浙江省", "")
print(test2.replace('sheng',''))